//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelEntities : DbContext
    {
        public ModelEntities()
            : base("name=ModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ChiTietOrders> tbl_ChiTietOrders { get; set; }
        public virtual DbSet<tbl_LoaiSanPhams> tbl_LoaiSanPhams { get; set; }
        public virtual DbSet<tbl_NguoiSuDungs> tbl_NguoiSuDungs { get; set; }
        public virtual DbSet<tbl_NhaSanXuats> tbl_NhaSanXuats { get; set; }
        public virtual DbSet<tbl_PhieuOrders> tbl_PhieuOrders { get; set; }
        public virtual DbSet<tbl_SanPhams> tbl_SanPhams { get; set; }
    }
}
