//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    public partial class tbl_SanPhams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SanPhams()
        {
            this.tbl_ChiTietOrders = new HashSet<tbl_ChiTietOrders>();
        }
    
        public int SanPhamID { get; set; }
        public string TenSanPham { get; set; }
        public string DungTich { get; set; }
        public Nullable<int> NongDo { get; set; }
        public Nullable<int> LoaiSanPhamID { get; set; }
        public Nullable<int> NhaSanXuatID { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> SoLanMua { get; set; }
        public Nullable<int> SoLanXem { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<bool> DaXoa { get; set; }
        public string MoTaNgan { get; set; }
        public string MoTaDai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ChiTietOrders> tbl_ChiTietOrders { get; set; }
        public virtual tbl_LoaiSanPhams tbl_LoaiSanPhams { get; set; }
        public virtual tbl_NhaSanXuats tbl_NhaSanXuats { get; set; }
    }
}
