//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChiTietOrders
    {
        public int ChiTietPhieuID { get; set; }
        public int PhieuOrderID { get; set; }
        public int SanPhamID { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public decimal ThanhTien { get; set; }
    
        public virtual tbl_PhieuOrders tbl_PhieuOrders { get; set; }
        public virtual tbl_SanPhams tbl_SanPhams { get; set; }
    }
}
